UKHomeOffice/brp_enquiry_forms

README.md, assets/css/_forms.scss, assets/css/app.scss, config/aws.json, controllers/start.js, controllers/submit.js, locales/en/default.json, models/submit.js, package.json, routes/fields.js, routes/index.js, routes/steps.js, services/ses-mailer.js, test/unit/controllers/start.js, test/unit/controllers/submit.js, views/layout.html, views/pages/index.html, views/pages/step1.html, views/pages/step2.html, views/partials/back.html, views/partials/form.html, views/partials/maincontent-left.html, views/partials/validation-list.html, views/partials/validation-summary.html
- templates
- form wizard
- controllers and tests
- some styles (sass)
- translations
=> DSP-15: Step one of the delivery journey

locales/en/default.json, package.json, routes/fields.js, routes/steps.js, views/pages/step1.html, views/pages/step2.html
- Update fields with pointers to locales
- Update to latest version of template wizard
=> Amendments to fields and template step1.html

locales/en/default.json, package.json, routes/fields.js, views/pages/step1.html, views/pages/step2.html
- add step2
- remove error/validation from step2.html
- define locales
- remove validation rules from fields/address-*
- make small amends to step1.html
=> DSP-16 Step 2 of the delivery journey

locales/en/default.json, routes/fields.js, routes/steps.js, views/pages/step1.html, views/pages/step2.html, views/pages/step3.html
- create step 3 page
- define fields for step 3
- define step 3 in steps.js
- update en/default.json translations
- make small amends to step 1 and 2 templates in accordance with requirements
=> DSP-17: Delivery journey Step 3 basic build

locales/en/default.json, routes/fields.js, routes/steps.js, views/pages/step4.html
- add step 4 template
- add releveant fields
- add translations
- amend links to incorporate step
=> BRP Delivery - Step 4

locales/en/default.json, routes/fields.js, routes/steps.js, views/pages/step1.html, views/pages/step2.html, views/pages/step5.html
- add step 5 template
- define step 5 route
- update field names
- update translations
=> Delivery: DSP-19 - step 5 of 6

locales/en/default.json, routes/fields.js, routes/steps/error.js, views/pages/about-error.html
- add new fields
- add translations
- update steps
=> Error flow one complete set of fields

package.json, routes/fields.js
- update gender-error field definition
=> update template mixin

Dockerfile, docker-compose.yml
- use latest nodejs (0.12.5) for building docker image
- add docker compose file
=> Add docker bits

routes/steps/delivery.js, routes/steps/error.js, views/layout.html, views/pages/confirmation.html
- remove backLink from both journeys
- connect steps
=> Amend confirmation page for permit error journey

LICENSE.md, package.json
If we're working in the open we should have a license on the application.
The government standard is MIT we should have a quick check if this is correct for HO.
=> Added MIT license.

LICENSE.md, package.json
If we're working in the open we should have a license on the application.
=> Added GPLv2 license.

controllers/letter-received.js, locales/en/default.json, test/unit/controllers/letter-received.js
- update translations for errors
- add future and format validating methods
- create delivery-date in process
- validate delivery-date separately
=> Validate future and mal-formatted dates

controllers/same-address.js, locales/en/default.json, routes/fields.js, routes/steps/delivery.js, test/unit/controllers/same-address.js, views/pages/same-address-details.html, views/pages/same-address.html
- update fields to be required
- add validation translations
- add custom controller to handle specific validation
https://jira.mgt.hod.homeoffice.gov.uk/browse/DSP-65
=> Validate permit delivery step 2 address matches

controllers/same-address.js, test/unit/controllers/same-address.js
- updated address matching condition, no means yes, yes means no!
=> Reverve validation criteria on address match

assets/scss/validation.scss, controllers/personal-details-passport.js, lib/date-controller.js, locales/en/default.json, routes/fields.js, routes/steps/delivery.js, test/unit/controllers/personal-details-passport.js, test/unit/lib/date-controller.js, views/pages/personal-details-passport.html
- update translations
- update stlyes
- remove date centric code from Personal Details Passpot controller
=> abstract date controller with validation

controllers/letter-received.js, controllers/personal-details-passport.js, lib/date-controller.js, test/unit/controllers/letter-received.js, test/unit/controllers/same-address.js
- use date controller for letter-received/personal-dateils page
- fix anomolies in date validation
=> Validate dates and page components

controllers/contact-details.js, locales/en/default.json, routes/fields.js, routes/steps/delivery.js, test/unit/controllers/contact-details.js, views/pages/contact-details.html
- custom controller
- validate fields under conditions
- add error messages/translations
=> validation of contact-details page

controllers/same-address.js, routes/steps/error.js, views/pages/same-address.html
- adjust logic
- add error list html mark up to other same-address template
=> fix up same address validation inc error journey

routes/steps/error.js
Add the controller to the steps definition in the error journey to add validation to the contact details page
=> Add controller to error journey contact details

app.js, config.js
Can be overriden using LISTEN_HOST env variable.
Fixes #51
=> Added a listen_host config property.

controllers/date-lost.js, controllers/letter-received.js, locales/en/default.json, routes/fields.js, routes/index.js, routes/steps/lost.js, views/pages/date-lost.html, views/pages/inside-uk.html
- create /inside-uk page
- create inside-uk and country fields
- set up validation
- add 'dependent' link between inside-uk and country fields
- create /date-lost page
- add wrapper controller with dateKey prop
- set up validation
=> DSP-89 & DSP-92

routes/steps/error.js, routes/steps/lost.js
- create personal details route in /steps/lost.js
=> DSP-93: lost or stolen - Personal details

locales/en/default.json, routes/fields.js, routes/steps/delivery.js, routes/steps/error.js, routes/steps/lost.js, views/pages/check-details-error.html, views/pages/check-details.html
- add check-details to lost or stolen journey
- renamed check-details-delivery
- updated check-details translations
- updated delivery and lost steps
- updated translations with errors and fields
- add new fields for organisation question
- updated all journeys with fields on check-details
=> dsp-95: lost-or-stolen/check-details

.eslintignore, .gitignore, Dockerfile, app.js, config.js, package.json, run.sh
To reduce confusion we now just create a public dir and mount to that in dev mode.
Updated the package.json to do all of this post install.
Updated the run.sh to reflect these changes.
=> Remove dist only use public dir

controllers/letter-received.js, locales/en/default.json, routes/steps/delivery.js, test/unit/controllers/letter-received.js, views/pages/letter-not-received.html
- create template
- create route
- test for form values to redirect
=> DSP-103: Delivery unhappy path - no decision

controllers/about-error.js, locales/en/default.json, routes/fields.js, routes/steps/error.js, test/unit/controllers/about-error.js, views/pages/about-error.html, views/pages/conditions-and-length.html
- add conditions-and-length template and route
- update anbout-error controller to redirect to apt route
=> DSP-104: Permit error unhappy path - conditions

locales/en/default.json, views/pages/check-details-error.html, views/pages/check-details.html, views/pages/contact-details.html
- DRY-up translations file
- update copy from prototype
- and panel-indent to organisation details section in check details pages
=> Update copy in delivery journey

locales/en/default.json
=> update error journey error messages

locales/en/default.json, routes/steps/lost.js
=> DSP-108: lost/stolen validation messages

services/email/templates/error_html.mus, views/pages/check-details.html
It shouldn't display the fields if they have no content.
=> Fixup bug in check-details page.

controllers/about-error.js, locales/en/default.json, routes/fields.js, routes/steps/error.js, test/unit/controllers/about-error.js
@ `/about-errors` do not check any box, click "continue", and see error message displayed in top list.
=> Display error when no errors are selected on about-errors page

config.js, controllers/check-details.js, locales/en/default.json, routes/steps/lost.js, services/email/index.js, services/email/templates/lost_or_stolen_html.mus, test/unit/controllers/check-details.js
=> Lost or stolen email

app.js, package.json
This is super simple right now but it allows us to have stdout logging in prod.
=> Add morgan for stdout logging.

config.js, locales/en/default.json, services/email/index.js, services/email/templates/caseworker/html/delivery.mus, services/email/templates/caseworker/html/error.mus, services/email/templates/caseworker/html/lost_or_stolen.mus, services/email/templates/caseworker/plain/delivery.mus, services/email/templates/caseworker/plain/error.mus, services/email/templates/caseworker/plain/lost_or_stolen.mus, services/email/templates/customer/html/delivery.mus, services/email/templates/customer/html/lost_or_stolen.mus, services/email/templates/customer/plain/delivery.mus, services/email/templates/customer/plain/lost_or_stolen.mus
This includes html and plain text versions.
Includes some slight refactoring to translation keys so they reuse makes more sense.
=> Caseworker emails

acceptance_tests/features/DSP-92.feature, acceptance_tests/features/DSP-96.feature, acceptance_tests/features/step_definitions/DSP-92_.steps.rb, acceptance_tests/features/support/config_test.yml
Fixes the error in travis and gets the acceptance tests up and running again
=> fix for DSP-92

locales/en/default.json
Reverts UKHomeOffice/brp_app#99
=> Revert "Update default.json"

config.js
Otherwise it will always be true
=> Fix bug in safe mode

config.js, documentation/ENVIRONMENT_VARIABLES.md, services/email/index.js
If the stmp_user field is empty then assume stub transport else use smtp transport.
=> Remove safe mode.

locales/en/default.json, routes/fields.js, routes/steps/lost.js, views/pages/correct-mistakes/check-details.html, views/pages/lost-or-stolen/check-details.html, views/pages/not-arrived/check-details.html, views/partials/org-type.html
- replace organistion field with org-type
- make org-type a partial
- include org-type in all three check-detail pages
=> Update organisation field

assets/js/countries/index.js, assets/js/index.js
allow for type ahead in other required fields.
=> Add eu countries

controllers/about-error.js, controllers/exit-truncated.js, controllers/personal-details.js, controllers/truncated.js, lib/date-controller.js, locales/en/default.json, routes/fields.js, routes/steps/error.js, test/unit/controllers/about-error.js, test/unit/controllers/exit-truncated.js, test/unit/controllers/truncated.js, test/unit/lib/date-controller.js, views/pages/correct-mistakes/check-details.html, views/pages/correct-mistakes/exit-truncated.html, views/pages/correct-mistakes/truncated.html
Truncated journey
- render truncated.html with title at correct-mistakes/truncated
- redirect to /truncate if either first or last name  or place of birth is too long
- move date formatting to date-controller
- format correct-mistakes date of birth
- handle user selections on save
- redirect to apt page
- add locale translations for truncated story
/*-----------------------------------------------------------------*/
Test according to: https://jira.digital.homeoffice.gov.uk/browse/DSP-115
=> Truncated journey: https://jira.digital.homeoffice.gov.uk/browse/DSP-115

app.js, config.js, package.json
- install `connect-redis-crypto`
- pass `secret` to RedisStore constructor at point of instantiation
=> encrypt session data with crypto before saving to Redis

routes/fields.js, views/pages/not-arrived/same-address-details.html
Fix toggling of content @ '/not-arrived/same-address`
=> replace toggle code

app.js, errors/index.js, locales/en/default.json, views/errors/error.html
This includes custom content for session_timeout errors.
=> Add error handler for 500 errors.

routes/index.js, views/cookies.html, views/layout.html, views/terms.html
Add Terms and conditions page.
Add links to both pages in the footer of the site.
=> Add cookies page.

controllers/check-details.js, services/email/index.js, services/email/templates/customer/html/lost_or_stolen_abroad.mus, services/email/templates/customer/html/lost_or_stolen_uk.mus, services/email/templates/customer/plain/lost_or_stolen_abroad.mus, services/email/templates/customer/plain/lost_or_stolen_uk.mus, test/unit/controllers/check-details.js
- add customer emails for abroad and uk
- update content in line with prototype
- send appropriate template based on users selected location
=> DSP-153: lost, stolen and damaged emails

lib/date-controller.js, test/unit/lib/date-controller.js
moment uses zero-indexed month values.
- subtract 1 from the user entered value for month
=> format month

assets/scss/app.scss, views/pages/correct-mistakes/personal-details-brp.html, views/pages/lost-or-stolen/personal-details.html, views/pages/not-arrived/personal-details.html
=> Fix year width for date inputs.

controllers/on-the-way.js, lib/base-controller.js, routes/steps/delivery.js, test/unit/lib/base-controller.js
- fix logic for reset session
- add reset false flag to journey page
=> Bugfix for letter-received/on-the-way exit scenario

app.js, errors/index.js, lib/logger.js, package.json
- logging errors
- logging requests
- removed debug logging
=> Simple logging with winston and churchill

assets/scss/app.scss
Ensure textarea widths are correcly sized (100%)
Ensure input widths are correctly sized (65%)
=> Styling fixes to field widths.

locales/en/default.json, routes/fields.js, routes/steps/delivery.js, routes/steps/error.js, routes/steps/lost.js, services/email/templates/caseworker/html/delivery.mus, services/email/templates/caseworker/html/error.mus, services/email/templates/caseworker/html/lost_or_stolen.mus, services/email/templates/caseworker/plain/delivery.mus, services/email/templates/caseworker/plain/error.mus, services/email/templates/caseworker/plain/lost_or_stolen.mus, services/email/templates/customer/html/delivery.mus, services/email/templates/customer/html/error.mus, services/email/templates/customer/html/lost_or_stolen_abroad.mus, services/email/templates/customer/html/lost_or_stolen_uk.mus, services/email/templates/customer/plain/delivery.mus, services/email/templates/customer/plain/error.mus, services/email/templates/customer/plain/lost_or_stolen_abroad.mus, services/email/templates/customer/plain/lost_or_stolen_uk.mus, views/pages/correct-mistakes/check-details.html, views/pages/correct-mistakes/contact-details.html, views/pages/lost-or-stolen/check-details.html, views/pages/lost-or-stolen/contact-details.html, views/pages/not-arrived/check-details.html, views/pages/not-arrived/contact-details.html
- address fields for contact address
- address fields for new address
=> Create second set of addres fields

locales/en/default.json, routes/fields.js, routes/steps/error.js, views/pages/correct-mistakes/about-error.html, views/pages/correct-mistakes/check-details.html, views/pages/correct-mistakes/contact-details.html, views/pages/correct-mistakes/location-applied.html, views/pages/correct-mistakes/personal-details-brp.html, views/pages/correct-mistakes/same-address.html
- increment all existing steps numbers
- create new template with locales
- add new fields and step definition
=> Add /location-applied page as step 1 of /correct-mistakes journey

controllers/about-error.js, locales/en/default.json, test/unit/controllers/about-error.js, views/pages/correct-mistakes/check-details.html, views/pages/lost-or-stolen/check-details.html, views/pages/not-arrived/check-details.html
- filter req.form.values
- unset diff
- check details list updated accordingly
- add phone field to '/check=details list'
- remove brp field from lost or stolen
=> Remove keys form model that have no value on '/about-error' saveValues

lib/base-controller.js
This fixes up all the problems we were having where we can't redirect to an error page.
=> Ensure that we can redirect when options.next is set and not just next.

routes/steps/delivery.js, routes/steps/error.js, routes/steps/lost.js, views/pages/correct-mistakes/confirmation.html, views/pages/lost-or-stolen/confirmation.html, views/pages/not-arrived/confirmation.html
=> Set done pages to GDS done pages.

acceptance_tests/features/DSP-103.feature, acceptance_tests/features/DSP-104.feature, acceptance_tests/features/DSP-22.feature, acceptance_tests/features/DSP-66.feature, acceptance_tests/features/DSP-67.feature, acceptance_tests/features/DSP-79.feature, acceptance_tests/features/DSP-81.feature, acceptance_tests/features/DSP-93.feature, acceptance_tests/features/DSP-94.feature, acceptance_tests/features/step_definitions/DSP-22_.steps.rb, acceptance_tests/features/step_definitions/DSP-67_.steps.rb
@AlexMurphy has done this:
``I've fixed the tests to take into account the names of the fields on step 4 of the forms have changed and that values in step 2 no longer persist to step 4.```
=> Fixup functional tests

assets/scss/app.scss, views/pages/correct-mistakes/check-details.html, views/pages/lost-or-stolen/check-details.html, views/pages/not-arrived/check-details.html
This fixes up widths and uses the correct color buttons.
=> Update styling on the check-details page.

controllers/collection-from.js, lib/date-controller.js, locales/en/default.json, routes/fields.js, routes/index.js, routes/steps/collection.js, test/unit/controllers/collection-from.js, test/unit/lib/date-controller.js, test/unit/test.js, views/pages/collection/confirmation.html, views/pages/collection/where.html
- add/update fields and steps
- add collection-from page elements (controller, view, locales)
- update date-controller, validateField to accepte required=false
=> Collection journey: && collection-from/where page (DSP-176)

locales/en/default.json
add missing validation message
=> add message

controllers/letter-received.js, lib/base-controller.js
Ensure we only try and validate the date fields if the user selects 'yes'
Remove debug and replace with logger.
Fixup a function typo.
=> Fixed bug on letter-recieved

locales/en/default.json, routes/fields.js, routes/steps/collection.js, views/pages/collection/reasons.html
- add collection/reasons page
- add reasons fileds, step def, template and translations
=> DSP-177: /collection/reasons

lib/base-controller.js, routes/steps/delivery.js
Added logging for when we're clearing sessions so we can see what endpoints are doing it
Clear session properly for on-the-way
=> Fix session not being cleared for on-the-way

routes/steps/collection.js, views/pages/collection/uk-address.html
- add template and localised content
- define route and assign steps
=> DSP-181: UK address for collection

locales/en/default.json, routes/fields.js, routes/steps/collection.js, views/pages/collection/personal-details.html
- add template and localised content
- define route and assign steps
- fix collection resaons field value
=> DSP-183: Collection - personal-details

routes/steps/collection.js, views/pages/collection/contact-details.html
- add template and localised content
- define route and assign fields and proeprties
=> DSP-182: Colection - /contact-details

assets/js/index.js, assets/scss/app.scss, controllers/someone-else.js, locales/en/default.json, routes/fields.js, routes/index.js, routes/steps/someone-else.js, test/unit/controllers/someone-else.js, views/pages/someone-else/arrange.html
* Add start page
* Add tests for custom controller
* Add content
=> Someone-else start page:

config.js, controllers/check-details.js, controllers/collection-check-details.js, locales/en/default.json, routes/steps/collection.js, routes/steps/delivery.js, routes/steps/error.js, services/email/templates/caseworker/html/collection.mus, services/email/templates/caseworker/plain/collection.mus, services/email/templates/caseworker/plain/delivery.mus, services/email/templates/caseworker/plain/error.mus, services/email/templates/caseworker/plain/lost_or_stolen.mus, services/email/templates/customer/html/collection.mus, services/email/templates/customer/plain/collection.mus, services/email/templates/customer/plain/delivery.mus, services/email/templates/customer/plain/error.mus, services/email/templates/customer/plain/lost_or_stolen_abroad.mus, services/email/templates/customer/plain/lost_or_stolen_uk.mus, test/unit/controllers/check-details.js, views/pages/collection/check-details.html, views/pages/collection/confirmation.html, views/pages/correct-mistakes/confirmation.html, views/pages/lost-or-stolen/confirmation.html, views/pages/not-arrived/confirmation.html
- save organisation details to session
- create collection emails
- config email service with new emails
=> Collection emails

services/email/templates/caseworker/html/error.mus, services/email/templates/caseworker/plain/error.mus, services/email/templates/customer/html/error.mus, services/email/templates/customer/plain/error.mus, views/pages/correct-mistakes/check-details.html
- add national-insurance number info to /check-details page
- add national-insurance number info to all relevant emails
=> DSP-192: Missing national-insurance number info

controllers/truncated.js, lib/base-controller.js, routes/steps/error.js, test/unit/controllers/truncated.js, test/unit/lib/base-controller.js
- set correct backLink from /uk-address
- fix setNextPage setting `next` property
- update `next` from same-address to 'uk-address' in saveValues
=> Fix issues with truncation and redirection

config.js, controllers/reason.js, controllers/someone-else-check-details.js, controllers/someone-else.js, locales/en/default.json, routes/fields.js, routes/steps/someone-else.js, services/email/index.js, services/email/templates/caseworker/html/someone-else.mus, services/email/templates/caseworker/plain/someone-else.mus, services/email/templates/customer/html/someone-else.mus, services/email/templates/customer/plain/someone-else.mus, test/unit/controllers/reason.js, test/unit/controllers/someone-else.js, views/pages/someone-else/arrange.html, views/pages/someone-else/check-details.html, views/pages/someone-else/confirmation.html, views/pages/someone-else/contact-details.html, views/pages/someone-else/exit-not-eligible.html, views/pages/someone-else/personal-details.html, views/pages/someone-else/reason.html
Remainder of the someone else journey.
Includes emails.
=> /someone-else journey

locales/en/default.json
@alex, check the new error message below and push the green button if it makes you happy
=> correct collection date error message

services/email/templates/caseworker/html/collection.mus, services/email/templates/caseworker/html/delivery.mus, services/email/templates/caseworker/html/error.mus, services/email/templates/caseworker/html/lost_or_stolen.mus, services/email/templates/caseworker/html/someone-else.mus
This existed on plain text but not html.
=> Add if help was required to all emails.

controllers/start.js, routes/steps/collection.js, routes/steps/delivery.js, routes/steps/error.js, routes/steps/lost.js, routes/steps/someone-else.js, views/pages/collection/check-details.html, views/pages/someone-else/check-details.html
- add start controller and assign to first step of each journey
- reset session and redirect to step one of each journey from start controller
- update 'change' button links that point to step one
- add 'redirectTo' property to step options because 'next' property has side-effects
=> DSP-202: Controller session reset with start controller

controllers/start.js, routes/steps/collection.js, routes/steps/delivery.js, routes/steps/error.js, routes/steps/lost.js, routes/steps/someone-else.js, test/unit/controllers/start.js
- call successHandler ->> emits 'complete' and redirects to this.options.next
- remove property `redirectTo` from steps
@easternbloc
=> Update start controller to call successHandler from getValues

lib/base-controller.js, routes/index.js, test/unit/controllers/confirmation.js, test/unit/controllers/on-the-way.js, test/unit/controllers/start.js, test/unit/controllers/truncated.js, test/unit/lib/base-controller.js, views/pages/collection/check-details.html, views/pages/correct-mistakes/check-details.html, views/pages/lost-or-stolen/check-details.html, views/pages/not-arrived/check-details.html, views/pages/someone-else/check-details.html
- update edit funcationality for /correct-mistakes
- Add edit to all 'change' button links
- returns to the page with /edit action, to trigger edit feature
=> fix edit funcationality

controllers/about-error.js, test/unit/controllers/about-error.js, views/pages/someone-else/check-details.html
- remove setNextPage from /about-error controller
- replace with getNextStep
- call parent getNextStep
- fix tests to make sure it works
- remove spurious characters from edit links
=> Fix exit pages from /correct-mistakes/about-error

locales/en/default.json
=> fix typo in code

apps/common/translations/en/default.json, apps/common/translations/src/en/errors.json, errors/index.js
- add error translations to apps/common
- update path from errors/index.js to apps/common/...
=> DSP-228: Error page translations

app.js, apps/collection/index.js, errors/index.js, lib/base-controller.js, lib/base-error.js, package.json, test/unit/lib/base-controller.js
- use hof in /collections app
- use hof - /lib
- use hof in app.js ('template')
=> Initial hof'ing

apps/correct-mistakes/index.js, apps/lost-stolen-damaged/index.js, apps/not-arrived/index.js, apps/someone-else/index.js
- use hof in correct-mistakes, lost-stoeln-damaged, not-arrived, someone-else
=> Use hof for remaining apps dsp-233

CONTRIBUTING.md
=> Add a contributing file.

assets/js/index.js, package.json
This removes the need to use browser fields in the package.json
=> Use latest version of hof

apps/common/translations/src/en/errors.json, config.js
=> Increase the session timeout to 30mins

apps/collection/steps.js, apps/correct-mistakes/steps.js, apps/lost-stolen-damaged/steps.js, apps/not-arrived/steps.js, apps/someone-else/steps.js
These are dereived from the step name
=> Remove unneeded template fields.

README.md
=> Fixing link on readme

apps/collection/views/confirm.html, apps/common/translations/src/en/footer.json, apps/correct-mistakes/translations/src/en/pages.json, apps/correct-mistakes/views/confirm.html, apps/lost-stolen-damaged/translations/src/en/pages.json, apps/lost-stolen-damaged/views/confirm.html, apps/not-arrived/translations/src/en/pages.json, apps/not-arrived/views/confirm.html, apps/someone-else/translations/src/en/pages.json, apps/someone-else/views/confirm.html
Couldn't replicate reported problems with terms and conditions link, but have extracted this bit of text to the common directory as it is the same for each journey
=> BRP-40 Extracted summary/confirm page footer details into common folder

Find Results, acceptance_tests/features/CollectionFormStep05ChangeDetails.feature, acceptance_tests/features/step_definitions/CollectionFormStep02_.rb, apps/collection/translations/src/en/fields.json, apps/correct-mistakes/translations/src/en/fields.json, apps/lost-stolen-damaged/translations/src/en/fields.json, apps/not-arrived/translations/src/en/fields.json, apps/someone-else/translations/src/en/pages.json
Getaway to Gateway
Changed Support organisation to Support oganisation/Charity
Changed example BRP number
=> Minor content changes

apps/collection/index.js, apps/correct-mistakes/index.js, apps/lost-stolen-damaged/index.js, apps/not-arrived/index.js, apps/someone-else/index.js, lib/field-default-attributes.js, package.json, test/unit/lib/field-default-attributes.js
Add new lib util that adds default attributes to fileds.
Add tests for new util.
=> Upgrade hof to support extending of attribuets on form fields.

Dockerfile
Lols and fun can be found here: https://github.com/docker/docker/issues/6119
For now we're just going to run transpile as root.
=> Docker COPY copies everything as root.

acceptance_tests/features/CollectionFormStep05ChangeDetails.feature, acceptance_tests/features/DeliveryFormStep02Validation.feature, acceptance_tests/features/LostStolenDamagedFormStep02Validation.feature, acceptance_tests/features/step_definitions/A_Common_Reusable_Steps.rb, acceptance_tests/features/step_definitions/CollectionFormConfirmationPage.rb, acceptance_tests/features/step_definitions/CollectionFormStep01_.rb, acceptance_tests/features/step_definitions/CollectionFormStep02_.rb, acceptance_tests/features/step_definitions/CollectionFormStep03_.rb, acceptance_tests/features/step_definitions/CollectionFormStep04_.rb, acceptance_tests/features/step_definitions/CollectionFormStep05_.rb, acceptance_tests/features/step_definitions/CollectionFormStep06_.rb, apps/collection/controllers/reason.js, apps/collection/fields/where.js, apps/collection/translations/src/en/fields.json, apps/collection/translations/src/en/pages.json, apps/correct-mistakes/translations/src/en/pages.json, apps/lost-stolen-damaged/translations/src/en/pages.json, apps/lost-stolen-damaged/translations/src/en/validation.json, apps/not-arrived/translations/src/en/journeys.json, apps/not-arrived/translations/src/en/pages.json, apps/someone-else/translations/src/en/pages.json
Minor tweaks, including softening of language around 5 working days to
respond, adding friends and family as people who can help, mentioning
that a vignette is a sticker
=> Further content changes post review

acceptance_tests/features/step_definitions/SomeoneElseFormStep02_.rb, apps/someone-else/fields/reason.js, apps/someone-else/translations/src/en/fields.json
=> Remove gateway refugee option from soneome-else

acceptance_tests/features/CollectionFormStep05ChangeDetails.feature, apps/collection/fields/reasons.js, apps/collection/steps.js, apps/collection/translations/src/en/fields.json, apps/collection/views/reasons.html, services/email/templates/caseworker/html/collection.mus, services/email/templates/caseworker/plain/collection.mus, services/email/templates/customer/html/collection.mus, services/email/templates/customer/plain/collection.mus
if they select "My BRP was not at the Post Office" no reason is required.
=> Removed reason from Post Office option

apps/collection/controllers/confirm.js, apps/collection/controllers/reason.js, apps/collection/fields/reasons.js, apps/collection/steps.js, apps/collection/translations/src/en/fields.json, apps/collection/views/confirm.html, apps/collection/views/reasons.html, services/email/templates/caseworker/html/collection.mus, services/email/templates/caseworker/plain/collection.mus, services/email/templates/customer/html/collection.mus, services/email/templates/customer/plain/collection.mus, test/unit/apps/collection/controllers/reason.js
=> Add I don't know which post office field to collection journey

acceptance_tests/features/CollectionFormChangeWithNominee.feature, acceptance_tests/features/CollectionFormStep05ChangeDetails.feature, acceptance_tests/features/step_definitions/ChangingCollectionFormDetails_.rb, acceptance_tests/features/step_definitions/ChangingDeliveryFormDetails_.rb, acceptance_tests/features/step_definitions/CollectionFormConfirmationPage.rb, acceptance_tests/features/step_definitions/CollectionFormStep03_.rb, acceptance_tests/features/step_definitions/CollectionFormStep04_.rb, acceptance_tests/features/step_definitions/CollectionFormStep05_.rb, acceptance_tests/features/step_definitions/CollectionFormStep06_.rb, acceptance_tests/features/step_definitions/DeliveryFormConfirmationPage.rb, apps/collection/controllers/reason.js, apps/collection/index.js, apps/collection/steps.js, package.json
[BRP-64](https://jira.digital.homeoffice.gov.uk/browse/BRP-64)
- update to hof latest
- update to use hof-controllers
- add fork condition
=> Add condition fork when reason radio others identity selected

acceptance_tests/features/step_definitions/CollectionFormStep06_.rb, acceptance_tests/features/step_definitions/ErrorFormConfirmationPage_.step.rb, acceptance_tests/features/step_definitions/SomeoneElseFormStep01_.rb, apps/collection/translations/src/en/pages.json, apps/collection/translations/src/en/validation.json, apps/correct-mistakes/translations/src/en/pages.json, apps/lost-stolen-damaged/translations/src/en/pages.json, apps/lost-stolen-damaged/translations/src/en/validation.json, apps/not-arrived/translations/src/en/pages.json, apps/not-arrived/translations/src/en/validation.json, apps/someone-else/translations/src/en/pages.json, apps/someone-else/translations/src/en/validation.json
[BRP-80](https://jira.digital.homeoffice.gov.uk/browse/BRP-80)
‘Organisation’ removed, as it could be friend or family member.
Changed content on content pages, as the wrong content was showing for
collection and nominate journeys
=> Confirmation page and organisation content changes

.travis.yml, apps/someone-else/fields/arrange.js, apps/someone-else/translations/src/en/pages.json, apps/someone-else/views/arrange.html, test/unit/apps/collection/controllers/reason.js
=> Reveal extra message if user cancels request.

acceptance_tests/features/step_definitions/CollectionFormStep02_.rb, acceptance_tests/features/step_definitions/LostStolenDamagedFormStep04.rb, acceptance_tests/features/step_definitions/SomeoneElseFormStep02_.rb, apps/collection/translations/src/en/fields.json, apps/collection/translations/src/en/pages.json, apps/lost-stolen-damaged/translations/src/en/journeys.json, apps/lost-stolen-damaged/translations/src/en/pages.json, apps/someone-else/translations/src/en/fields.json
Removed word disability
Corrected confirmation page for collection
lower case R and A on responsible adult
=> Changes made post test run

acceptance_tests/features/ErrorFormStep04Validation.feature, acceptance_tests/features/step_definitions/A_Common_Reusable_Steps.rb, acceptance_tests/features/step_definitions/ChangingErrorFormDetails_.rb, acceptance_tests/features/step_definitions/ErrorFormConfirmationPage_.step.rb, acceptance_tests/features/step_definitions/ErrorFormStep05.rb, acceptance_tests/features/step_definitions/ErrorFormStep06.rb, apps/correct-mistakes/fields/index.js, apps/correct-mistakes/fields/personal-details.js, apps/correct-mistakes/translations/src/en/fields.json, apps/correct-mistakes/translations/src/en/validation.json
In country - Error - Step 3 - Make BRP card number compulsor
=> [BRP-69] Error - Make BRP card number compulsory

acceptance_tests/features/ErrorFormStep02LetterExitPage.feature, acceptance_tests/features/ErrorFormStep02Validation.feature, acceptance_tests/features/step_definitions/ErrorFormStep02LetterExitPage_.step.rb, apps/correct-mistakes/controllers/about-error.js, apps/correct-mistakes/fields/about-error.js, apps/correct-mistakes/steps.js, apps/correct-mistakes/translations/src/en/fields.json, apps/correct-mistakes/translations/src/en/pages.json, apps/correct-mistakes/translations/src/en/validation.json, apps/correct-mistakes/views/about-error.html, apps/correct-mistakes/views/enrolment-letter.html, test/unit/apps/correct-mistakes/controllers/about-error.js
"In country - Error - Add the Enrollment letter as one of the error
options – but if people select it, take them to an exit page and explain
what to do to report a problem with their letter."
=> [BRP-70] Add "Enrolment letter" error option

apps/correct-mistakes/translations/src/en/fields.json, apps/correct-mistakes/views/confirm.html, services/email/templates/caseworker/html/error.mus, services/email/templates/caseworker/plain/error.mus, services/email/templates/customer/html/error.mus, services/email/templates/customer/plain/error.mus, test/unit/apps/correct-mistakes/controllers/about-error.js
* Add "Enrolment letter" to /correct-mistakes/confirm page
* Add "Enrolment letter" to "error" e-mail templates
* Misc clean-up
=> [BRP-70] Update confirm page and e-mail templates

Dockerfile, config.js, run.sh
* Fixes bug in the docker build.
* Adds initial support for docker compose.
Must be tested in kubernetes!
=> Docker compose

acceptance_tests/features/ErrorFormStep02ConditionsExitPage.feature, acceptance_tests/features/ErrorFormStep02LetterExitPage.feature, acceptance_tests/features/ErrorFormStep02Validation.feature, apps/correct-mistakes/fields/about-error.js, apps/correct-mistakes/views/about-error.html
- remove fields
- remove view refs to fields
- amend tests
=> BRP-82: remove text boxes for 'conditions' and 'letter' on /about-error

acceptance_tests/features/step_definitions/ErrorFormStep02LetterExitPage_.step.rb, apps/correct-mistakes/translations/src/en/pages.json
=> BRP-102: Update enrolment-letter page content.

app.js, apps/common/translations/src/en/errors.json, apps/common/views/404.html, errors/index.js, middleware/not-found.js
- add route for 404's
- add page for 404's
- add translations for 404 message
=> BRP-87: 404 page

errors/index.js
=> BRP-107: Express expects erroHandler function to have arity of 4

apps/collection/views/confirmation.html, apps/someone-else/views/confirmation.html
- update /collection with a done link address
- update /someone-else with a done link address
=> BRP-83: Update journeys with done links

acceptance_tests/features/CollectionFormStep05ChangeDetails.feature, acceptance_tests/features/step_definitions/CollectionFormStep02_.rb, apps/collection/controllers/confirm.js, apps/collection/controllers/reason.js, apps/collection/fields/reasons.js, apps/collection/steps.js, apps/collection/translations/src/en/fields.json, apps/collection/views/confirm.html, apps/collection/views/reasons.html, services/email/templates/caseworker/html/collection.mus, services/email/templates/caseworker/plain/collection.mus, services/email/templates/customer/html/collection.mus, services/email/templates/customer/plain/collection.mus
=> Remove option from post office route on collection

apps/correct-mistakes/steps.js
This stops people getting through the form when they shouldn't
=> Ensure sessions are cleared for exit pages.

acceptance_tests/features/SomeoneElseFormStep01Validation.feature, acceptance_tests/features/step_definitions/SomeoneElseFormConfirmationPage_.rb, acceptance_tests/features/step_definitions/SomeoneElseFormStep02_.rb, acceptance_tests/features/step_definitions/SomeoneElseFormStep03_.rb, acceptance_tests/features/step_definitions/SomeoneElseFormStep04_.rb, acceptance_tests/features/step_definitions/SomeoneElseFormStep05_.rb, apps/someone-else/fields/arrange.js, apps/someone-else/steps.js, apps/someone-else/translations/src/en/fields.json, apps/someone-else/translations/src/en/pages.json, apps/someone-else/translations/src/en/validation.json, apps/someone-else/views/arrange.html, apps/someone-else/views/confirm.html, services/email/templates/caseworker/html/someone-else.mus, services/email/templates/caseworker/plain/someone-else.mus, services/email/templates/customer/html/someone-else.mus, services/email/templates/customer/plain/someone-else.mus
=> Add new document-type to the someone else journey

assets/countries/index.js
Countries list has been updated and cleaned up / simplified.
It has also been sorted to improve UX.
=> [BRP-94] Update countries lists and sort

app.js, config.js, docker-compose.yml, services/email/index.js
Initial support for catching e-mails for testing purposes using
docker-compose.
NOTE: This probably needs to be discussed then modified prior to being merged in. (We also should try to find a way to run nginx at the same time as MailDev. - They currently clash.)
=> Maildev via docker-compose

README.md
Added a comment in the README file to make sure there is a running redis
instance in the background before starting up the server.
=> Added a comment in the README about Redis

acceptance_tests/features/step_definitions/DeliveryFormStep01NoDecisionExitPage.rb, acceptance_tests/features/step_definitions/DeliveryFormStep01NoLetterExitPage.rb, apps/not-arrived/translations/src/en/pages.json, apps/not-arrived/views/letter-lost.html
This gives the user more than one option of contact instead of just a phone number.
=> Update text for lost-letter page.

services/email/templates/caseworker/html/collection.mus, services/email/templates/caseworker/html/delivery.mus, services/email/templates/caseworker/html/lost_or_stolen.mus, services/email/templates/caseworker/html/someone-else.mus, services/email/templates/caseworker/plain/collection.mus, services/email/templates/caseworker/plain/delivery.mus, services/email/templates/caseworker/plain/lost_or_stolen.mus, services/email/templates/caseworker/plain/someone-else.mus, services/email/templates/customer/html/collection.mus, services/email/templates/customer/html/delivery.mus, services/email/templates/customer/html/lost_or_stolen_abroad.mus, services/email/templates/customer/html/lost_or_stolen_uk.mus, services/email/templates/customer/html/someone-else.mus, services/email/templates/customer/plain/collection.mus, services/email/templates/customer/plain/delivery.mus, services/email/templates/customer/plain/lost_or_stolen_abroad.mus, services/email/templates/customer/plain/lost_or_stolen_uk.mus, services/email/templates/customer/plain/someone-else.mus
This adds all the missing house numbers from all the journeys.
=> We were missing the house number from ALOT of emails.

apps/collection/views/personal-details.html
Fixed broken aria-describedby reference on date input, like on #341.
This might be a problem on hof to fix as well.
=> Fixed broken aria reference

package.json
This combined with gzip makes things small.
=> Uglify the browserify bundle.

app.js, apps/common/views/layout.html, config.js
If GA_TAG is available we will add it to the analytics.
=> Add GA tag from GA_TAG env variable.

apps/collection/views/confirm.html, apps/correct-mistakes/views/confirm.html, apps/lost-stolen-damaged/views/confirm.html, apps/not-arrived/views/confirm.html, apps/someone-else/views/confirm.html, assets/scss/app.scss
=> Use h2 instead of h3 on confirmation page

apps/common/fields/contact-details.js
=> Make the checkbox hit area bigger.

apps/collection/translations/src/en/pages.json, apps/collection/views/confirmation.html, apps/common/views/partials/confirmation-banner.html, apps/correct-mistakes/translations/src/en/pages.json, apps/correct-mistakes/views/confirmation.html, apps/lost-stolen-damaged/translations/src/en/pages.json, apps/lost-stolen-damaged/views/confirmation.html, apps/not-arrived/translations/src/en/pages.json, apps/not-arrived/views/confirmation.html, apps/someone-else/translations/src/en/pages.json, apps/someone-else/views/confirmation.html, assets/scss/app.scss
Moved email address (if provided) into the confirm banner as per BRP-144
=> Refactored the confirm pages to use a confirm-banner partial.

apps/collection/controllers/nominee.js, apps/collection/controllers/personal-details.js, apps/collection/controllers/where.js, apps/common/controllers/confirm.js, apps/common/controllers/confirmation.js, apps/common/controllers/start.js, apps/correct-mistakes/controllers/about-error.js, apps/correct-mistakes/controllers/truncated.js, apps/correct-mistakes/controllers/uk-address.js, apps/lost-stolen-damaged/controllers/date-lost.js, apps/not-arrived/controllers/on-the-way.js, apps/someone-else/controllers/confirm.js, apps/someone-else/controllers/personal-details.js, apps/someone-else/controllers/reason.js, test/unit/apps/collection/controllers/personal-details.js, test/unit/apps/collection/controllers/where.js, test/unit/apps/common/controllers/confirm.js, test/unit/apps/common/controllers/confirmation.js, test/unit/apps/common/controllers/start.js, test/unit/apps/correct-mistakes/controllers/about-error.js, test/unit/apps/correct-mistakes/controllers/truncated.js, test/unit/apps/lost-stolen-damaged/controllers/date-lost.js, test/unit/apps/someone-else/controllers/personal-details.js, test/unit/apps/someone-else/controllers/reason.js
Updates *all* controllers to use the hof-controllers
=> Update controllers to use hof.controllers

assets/js/index.js, package.json
This has better support for aria and tries to offer more help in a typeahead element.
=> Use the new typeahead-aria module

.travis.yml, Dockerfile, app.js, package.json
This allows us to update to the latest version of hof 7.0
=> Upgrade node version

acceptance_tests/features/SomeoneElseFormStep01Validation.feature, apps/collection/fields/nominee.js, apps/collection/fields/reasons.js, apps/collection/translations/src/en/fields.json, apps/common/fields/contact-details.js, apps/common/fields/organisation-details.js, apps/common/fields/personal-details.js, apps/correct-mistakes/fields/about-error.js, apps/correct-mistakes/fields/personal-details.js, apps/correct-mistakes/translations/src/en/fields.json, apps/lost-stolen/translations/src/en/fields.json, apps/not-arrived/translations/src/en/fields.json, apps/someone-else/fields/arrange.js, apps/someone-else/translations/src/en/fields.json, apps/someone-else/translations/src/en/pages.json, assets/countries/index.js, assets/js/index.js, assets/scss/app.scss
This PR also removes lots of hints that weren't needed.
It also updates a bit of copy on the someone-else journey.
=> Add more hidden text for type ahead

apps/collection/translations/src/en/pages.json, apps/common/translations/src/en/common-fields.json, apps/common/translations/src/en/validation.json, apps/common/views/terms.html, apps/correct-mistakes/translations/src/en/fields.json, apps/correct-mistakes/translations/src/en/pages.json, apps/correct-mistakes/translations/src/en/validation.json, apps/lost-stolen/translations/src/en/pages.json, apps/not-arrived/translations/src/en/pages.json, apps/someone-else/translations/src/en/pages.json
=> June-content-changes

apps/correct-mistakes/fields/about-error.js, apps/correct-mistakes/views/about-error.html, apps/correct-mistakes/views/confirm.html
Gender was not preserving across pages
=> Conditions and length of stay were not getting propogated.

apps/collection/translations/src/en/buttons.json, apps/correct-mistakes/translations/src/en/buttons.json, apps/lost-stolen/translations/src/en/buttons.json, apps/not-arrived/translations/src/en/buttons.json, apps/someone-else/translations/src/en/buttons.json
=> Reworded hidden change buttons

acceptance_tests/features/CollectionFormStep05Validation.feature, acceptance_tests/features/DeliveryFormStep04Validation.feature, acceptance_tests/features/ErrorFormStep05Validation.feature, acceptance_tests/features/LostStolenDamagedFormStep04Validation.feature, acceptance_tests/features/SomeoneElseFormStep04Validation.feature, acceptance_tests/features/step_definitions/A_Common_Reusable_Steps.rb, acceptance_tests/features/step_definitions/CollectionFormStep05_.rb, acceptance_tests/features/step_definitions/DeliveryFormStep04.rb, acceptance_tests/features/step_definitions/SomeoneElseFormStep04_.rb, apps/collection/translations/src/en/fields.json, apps/correct-mistakes/translations/src/en/fields.json, apps/lost-stolen/translations/src/en/fields.json, apps/not-arrived/translations/src/en/fields.json, apps/someone-else/translations/src/en/fields.json
We now say 'I want to be contacted by post'
=> Change wording for 'I do not have an email address'

apps/collection/translations/src/en/emails.json, apps/correct-mistakes/translations/src/en/emails.json, apps/correct-mistakes/translations/src/en/pages.json, apps/correct-mistakes/views/confirmation.html, apps/lost-stolen/translations/src/en/emails.json, apps/not-arrived/translations/src/en/emails.json, apps/someone-else/translations/src/en/emails.json, services/email/templates/customer/html/collection.mus, services/email/templates/customer/html/delivery.mus, services/email/templates/customer/html/error.mus, services/email/templates/customer/html/lost_or_stolen_abroad.mus, services/email/templates/customer/html/lost_or_stolen_uk.mus, services/email/templates/customer/html/someone-else.mus, services/email/templates/customer/plain/collection.mus, services/email/templates/customer/plain/delivery.mus, services/email/templates/customer/plain/error.mus, services/email/templates/customer/plain/lost_or_stolen_abroad.mus, services/email/templates/customer/plain/lost_or_stolen_uk.mus, services/email/templates/customer/plain/someone-else.mus
Also update error journey so that the triage process informs the user of 1 working day
=> Remove all personal data from the customer email

Dockerfile
This fixes an issue in our dockerfile
```Error: Cannot find module 'govuk_template_mustache/views/layouts/govuk_template.html'```
=> Use npm 3 for our dependencies.

apps/common/views/layout.html
=> We passed out live service assessment so we no longer need a beta banner!!!

package.json
This means that postinstall will only pass when all of the stages pass
and not just the last.
=> Update postinstall script to fail early

apps/collection/translations/src/en/emails.json, services/email/templates/customer/html/collection.mus, services/email/templates/customer/plain/collection.mus
This adds a message informing users about the closure of oxford street post office.
=> Update the response copy in the collection email

apps/lost-stolen/translations/src/en/emails.json, services/email/templates/caseworker/html/lost_or_stolen.mus, services/email/templates/caseworker/plain/lost_or_stolen.mus, services/email/templates/customer/html/lost_or_stolen_abroad.mus, services/email/templates/customer/html/lost_or_stolen_uk.mus, services/email/templates/customer/plain/lost_or_stolen_abroad.mus, services/email/templates/customer/plain/lost_or_stolen_uk.mus
=> New copy for lost stolen emails

apps/correct-mistakes/translations/src/en/emails.json, apps/correct-mistakes/translations/src/en/pages.json, apps/lost-stolen/translations/src/en/pages.json
=> Update turnaround times as per latest requirements from BRP team

apps/common/controllers/confirm.js, apps/lost-stolen/translations/src/en/emails.json, docker-compose.yml, services/email/templates/customer/html/lost_or_stolen_uk.mus, services/email/templates/customer/plain/lost_or_stolen_uk.mus, test/unit/apps/common/controllers/confirm.js
This stopped the templates being looked up if someone adds a GET param onto the requst.
Also fixed some translation issues.
Add new docker-compose setup using nginx and maildev
=> Fix bugs in email due to GET params

apps/lost-stolen/views/confirm.html, services/email/templates/caseworker/html/collection.mus, services/email/templates/caseworker/html/delivery.mus, services/email/templates/caseworker/html/error.mus, services/email/templates/caseworker/html/someone-else.mus, services/email/templates/caseworker/plain/collection.mus, services/email/templates/caseworker/plain/delivery.mus, services/email/templates/caseworker/plain/someone-else.mus
This will fix missing fields from both summary pages and emails
=> Remove the -formatted key which no longer exists.

assets/js/index.js, errors/index.js, package.json
* update eslint-homeoffice-config
* fix linting warnings
=> Fix eslint issues

.drone.yml, Dockerfile
because https://github.com/UKHomeOffice/docker-nodejs-base/pull/19/files
=> Update to node v8

README.md, package-lock.json
Jira Ticket: https://collaboration.homeoffice.gov.uk/jira/browse/SD-36
Testing build and deployment of BRP form. 
**Changes**
1. Updated readme file to contain information of tested `redis` and `npm` versions to get the BRP form running locally.
=> SD-36: Added redis server and npm version numbers to readme

services/email/templates/customer/plain/delivery.mus
https://collaboration.homeoffice.gov.uk/jira/browse/SD-106
This is a change requested by the BRP team to change the content on the lost-stoled card response email. The new content is specified within the ticket above.
=> SD-106: Update delivey email content

README.md
Update Readme:
* explaining how to test email locally.  
* added a contents section 
* Testing email locally saves a lot of time
=> SD-120 Readme: add how to test email locally

README.md
Update the readme for testing email locally.  Add a missing environment variable
Otherwise you might get an `Error: self signed certificate in certificate chain.` https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain
=> SD-120 ReadMe: test email locally, add environment variable

.drone.yml
**Jira Ticket**: https://collaboration.homeoffice.gov.uk/jira/browse/SD-124
**Changes**: Updated drone.yaml file to version 1
=> SD-124: Update drone version 1

apps/not-arrived/translations/src/en/emails.json
=> SDS-296: Update delivery email header

.drone.yml, Dockerfile, package-lock.json, package.json
- Updated node version in drone file and docker file.
- Node 10 is no longer supported and security issues may be introduced
=> Upgrade node version to 14

acceptance_tests/Gemfile.lock
What
Upgraded rack 
Why
To fix security vulnerability
How
Updated the package to later secure version
=> Upgrade packages to resolve critical and high vulnerabilities

services/email/templates/customer/html/delivery.mus, services/email/templates/customer/plain/delivery.mus
-update to the content of the email for the not-arrived route to feature longer waiting time and new information
=> SD-817 update not arrived email content

apps/not-arrived/translations/src/en/pages.json, apps/not-arrived/views/confirmation.html
-update to the content of the confirmation page of the not-arrived route to feature new information
=> SD-818 update not arrived confirmation page content

apps/not-arrived/translations/src/en/pages.json
- reflect 40 days instead of 5 to respond in busy periods
=> SD-818 - update to content in pages.json

services/email/templates/customer/plain/delivery.mus
What
- add 'this is an automated email...' line to end of plain email template to match html email template.
=> update not-arrived email content in plain email template

package.json, yarn.lock
Update HOF
Old version had security vulnerabilities
=> BRP-36: Update HOF and Snyk

.drone.yml
An update to allow publishing of a cucumber report on deployment to branch evironment
BRP reports available here:
https://reports.cucumber.io/report-collections/65ed5af9-323e-4bfb-ae20-48c7fb3d3a95
updated drone.yml with command and environemnt variable from cucmber collection
=> BRP-37 enable cucumber reporting on branch

.snyk, package.json, yarn.lock
update hof version to 19.11.23
=> BRP-update-hof-version

apps/not-arrived/index.js, apps/not-arrived/views/collection.html
Changed incorrect journey header on landing page.
Bug
Forced template render in the journey index file to collection.html and changed the html file accordingly.
Ran unit, acceptance and lint tests locally.
=> Resolve incorrect journey header

apps/not-arrived/behaviours/change-path.js, apps/not-arrived/index.js
Fix for reroute that was failing on internet explorer
Fix for when the post-office-collect page was showing the letter-lost page when a date was entered
=> BRP-6-fix-for-IE

hof.settings.json, package.json, test/_features/brp/correct_mistakes.feature, yarn.lock
Fix incorrect cookie banner
Cookie banner is incorrect - cookie banner says 'Residency' at the banner level but should say 'Residence'.
Amended 'Residency' to 'Residence'
Tested locally
=> brp-38: fix incorrect cookie banner

apps/not-arrived/fields/consignment-number.js, apps/not-arrived/translations/src/en/validation.json
Adding notUrl validator to consignment number text input and corresponding validator message.
Adding hof validator in consignment-number.js and validation message in validation.json
Running lint, unit and acceptance tests locally.
=> BRP-63-fix - Add notUrl validator and validator message to consignment-number input

.snyk, package.json, yarn.lock
HOFF-257 - Updated HOF to enable GA4
=> HOFF-257 - updated HOF to enable GA4

services/email/templates/caseworker/html/collection.mus
**Changes**	
- Collection.mus changed to correct phone number field to "None Given"
=> BRP-95: Spelling correction for phone number field

apps/collection/translations/src/en/pages.json, apps/correct-mistakes/translations/src/en/validation.json, package.json, yarn.lock
Hotfix to add missing translation
=> BRP-108 Added missing translation

.snyk, apps/common/behaviours/email.js, config.js, test/_unit/apps/common/behaviours/email.spec.js
Added config and logic to send BIDMU email
=> Added BIDMU email submission

apps/common/behaviours/email.js, services/email/index.js, test/_unit/apps/common/behaviours/email.spec.js, test/_unit/apps/common/services/emailService.spec.js
Corrected minor issue with BRP-111 implementation to ensure we send the correct email
=> BRP-111 Adjusted integration email logic

config.js, server.js, yarn.lock
- Update link to feedback form - [BRP-142](https://collaboration.homeoffice.gov.uk/jira/browse/BRP-142)
- per business request to allow users to complete the latest version of the feedback form
- add FEEDBACK_URL environment variable to config.js
- change hardcoded feedback url in server.js to config.feedbackUrl to make url dynamic
tested locally and on branch
- update yarn.lock
=> BRP-142: Update link to feedback form

.drone.yml, package.json, yarn.lock
[BRP-155](https://collaboration.homeoffice.gov.uk/jira/browse/BRP-155) - Update to latest HOF version
Allow for smoother development, less bugs.
- Updated packadge.json
- updated yarn.lock
Tested on local machine 
=> BRP-155 Update to latest HOF version
