UKHomeOffice/brp_enquiry_forms

locales/en/default.json
routes/steps/error.js
views/pages/contact-details.html

- add contact-details as a step in /permit-error
- remove steps.four.* from translations file
- add pages.contact-details to translations file
- update template with correct translations
- add subheader to contact-details template

Permit error step 4/contact details

---

acceptance_tests/Gemfile.lock
assets/scss/app.scss
assets/scss/validation.scss
controllers/letter-received.js
locales/en/default.json
package.json
routes/fields.js
routes/steps/delivery.js
test/.eslintrc
test/unit/controllers/letter-received.js
views/pages/letter-received.html
views/partials/validation-summary.html

This pr covers the validation display of error messages for the initial form page of the `undelivered` journey.
Items validated:
- is the letter received radio buttons: a user must select a button.
- if the user selects no to the previous control, then the date is validated: date is required and must be numeric.
Error messages are displayed at field level where appropriate and in a list at the top of the form/page

Validation permit delivery

---

Dockerfile
run.sh

Contents of the `assets` directory have to be copied on to a volume which kubernetes creates for a pod. nginx container in the same pod will then serve static assets.

Add run.sh for assets contents copying

---

Dockerfile

Unfortunately we're going to have to run node as root, because run.sh
needs to be able to copy assets to /public which is owned by root.

node 0.12.7 and fix assets copying

---

controllers/confirmation.js
locales/en/default.json
routes/steps/delivery.js
routes/steps/error.js
routes/steps/lost.js
test/unit/controllers/confirmation.js
views/pages/check-details-error.html
views/pages/confirmation-lost.html
views/pages/confirmation.html

- add confirmation controller to serve locals for location setting
- add confirmation translations and format consistently
- add new confirmation controller to each journey
- add check-details-error template org-help form control

DSP-96: lost or stolen confirmation content variations

---

services/email/index.js

Fix issue that happened after a refactor.
This fix ensures that the email goes the correct person both client and caseworker.

Send emails to the correct customer/client

---

assets/js/index.js
assets/scss/app.scss
package.json
services/countries/index.js

Based on the gds implementation of typeahead using twitters typeahead.
Styling should look close to gds style.
List of 'countries' is our own. This list needs refining I'm sure.

Type ahead.

---

controllers/about-error.js
controllers/check-details.js
controllers/confirmation.js
controllers/contact-details.js
controllers/letter-received.js
controllers/on-the-way.js
controllers/same-address.js
controllers/start.js
lib/base-controller.js
lib/base-error.js
lib/base-wizard.js
lib/date-controller.js
locales/en/default.json
routes/index.js
test/unit/lib/date-controller.js
views/partials/validation-summary.html

- add base-error, base-wizard, and base-controller modules
- hook base wizard to routes
- rewire custom constructors to base-controller and base-error where apt.
- override controller.prototype.locals to provide error list length to view
- update validation summary view to conditionally display apt message
- add/amend errorlist messages in locales

Base Constructors - easier extension

---

controllers/about-error.js
routes/fields.js
test/unit/controllers/about-error.js

- use dependent option on all necessary field for '/about-error' where possible
- do not use dependent option for date fields
- reorganise about-error validation to avoid dependency checking for all but dates

Use form controller 'dependent' option where possible

---

config.js
documentation/ENVIRONMENT_VARIABLES.md
services/email/index.js

This sets up the env variables we need for the three caseworker emails.
If no env var is set up it uses a broken caseworker address.
Updated docs.

Allow multiple caseworker email addresses to be supported in the application

---

.travis.yml
app.js

Changed the NODE_ENV from travis to ci to be less tied into using travis.

Disable logging when running tests in a ci

---

package.json

Replaces the brace expansion in the create:public script in package.json.
Brace expansions are a Bash extension. npm runs its scripts through sh not bash.
On most modern GNU/Linux distributions sh is symlinked to bash which is why the
brace expansion will work in most cases. However, this is not always the case;
for example Ubuntu symlinks sh to dash which does not support bash completion.
This means that 'npm run create:public' fails and with it 'npm install'.

Eliminate reliance on Bash

---

lib/logger.js

Makes easy parsing of logging by other tools.
Closes #226

Enable single line JSON output

---

apps/common/models/email.js
assets/js/index.js
assets/scss/app.scss
package.json
services/email/index.js
test/unit/apps/common/models/email.js

- remove dependencies from BRP that are installed via HOF
- update @import path in app.scss
- update all paths to node_modules/hof...
- use browser field in BRP to point hof at hmpo-frontend-toolkit for browserify

DSP-242: Remove dependencies that have been repalced with HOF

---

services/email/index.js

This is because the locations of the translations are now within the sub apps
This fix now resolves the translation when .send() is called which allows for mutliple translation locations to be used

Email translations were not working post refactor.

---

services/email/index.js

This was causing bugs on the emails as the translation file was not loaded when the first email was being sent.
Only has become and issue now as we dynamically load translations based on the journey.

Only send the emails when the translation file has loaded.

---

.nodemonignore
services/email/templates/customer/html/collection.mus
services/email/templates/customer/html/delivery.mus
services/email/templates/customer/html/someone-else.mus
services/email/templates/customer/plain/collection.mus
services/email/templates/customer/plain/delivery.mus
services/email/templates/customer/plain/someone-else.mus

This is a security concern in case the user typos their email address.

Remove passport number from customer emails.

---

package.json

This removes the circular dependency in hof with hof-controllers and hof.
Stops quay failing as the previous version required git.

Update hof to the latest version.

---

Dockerfile

As we copy the app after the npm install the translations don't exist yet so transpile wasn't working
In order to keep docker caching the image quickly we don't want to npm install after copying the app so we're just adding this step afterwards (quicker docker images).

Add new hof-transpile step to dockerfile

---

acceptance_tests/features/CollectionFormStep06Validation.feature
acceptance_tests/features/step_definitions/A_Common_Reusable_Steps.rb
app.js
apps/collection/steps.js
apps/common/fields/organisation-details.js
apps/common/translations/src/en/fields.json
apps/common/translations/src/en/validation.json
apps/common/views/partials/org-type.html
apps/correct-mistakes/steps.js
apps/lost-stolen-damaged/steps.js
apps/not-arrived/steps.js
apps/someone-else/steps.js
package.json
services/email/index.js
services/email/templates/caseworker/html/collection.mus
services/email/templates/caseworker/html/delivery.mus
services/email/templates/caseworker/html/error.mus
services/email/templates/caseworker/html/lost_or_stolen.mus
services/email/templates/caseworker/html/someone-else.mus
services/email/templates/caseworker/plain/collection.mus
services/email/templates/caseworker/plain/delivery.mus
services/email/templates/caseworker/plain/error.mus
services/email/templates/caseworker/plain/lost_or_stolen.mus
services/email/templates/caseworker/plain/someone-else.mus
services/email/templates/customer/plain/collection.mus
services/email/templates/customer/plain/delivery.mus
services/email/templates/customer/plain/error.mus
services/email/templates/customer/plain/lost_or_stolen_abroad.mus
services/email/templates/customer/plain/lost_or_stolen_uk.mus
services/email/templates/customer/plain/someone-else.mus

This PR adds an optional e-mail field to the 3rd party and the end of each of the journeys and exposes this information in the e-mails when it is available.
It also includes a fix me prevent silent failure when sending the case-worker e-mail. (For example when the address is invalid.)
The version of hof-transpiler is also bumped.
As this PR touches many files, all journeys and the e-mails (which exist outside of our automated testing!) a code review would be appreciated.

[BRP-76] Add email field to 3rd party

---

services/email/templates/caseworker/html/collection.mus
services/email/templates/caseworker/html/delivery.mus
services/email/templates/caseworker/html/error.mus
services/email/templates/caseworker/html/lost_or_stolen.mus
services/email/templates/caseworker/html/someone-else.mus
services/email/templates/caseworker/plain/collection.mus
services/email/templates/caseworker/plain/delivery.mus
services/email/templates/caseworker/plain/error.mus
services/email/templates/caseworker/plain/someone-else.mus
services/email/templates/customer/plain/collection.mus
services/email/templates/customer/plain/delivery.mus
services/email/templates/customer/plain/error.mus
services/email/templates/customer/plain/lost_or_stolen_abroad.mus
services/email/templates/customer/plain/lost_or_stolen_uk.mus
services/email/templates/customer/plain/someone-else.mus

Expand the org-type with a translation to give a little more description in the caseworker email.
Remove some fields from customer emails that are not required.

Tidy up emails

---

acceptance_tests/features/DeliveryFormStep01NoLetterExitPage.feature
acceptance_tests/features/step_definitions/DeliveryFormStep01NoLetterExitPage.rb
acceptance_tests/features/step_definitions/DeliveryFormStep02.rb
apps/not-arrived/controllers/letter-received.js
apps/not-arrived/fields/letter-received.js
apps/not-arrived/index.js
apps/not-arrived/steps.js
apps/not-arrived/translations/src/en/pages.json
apps/not-arrived/views/letter-lost.html
errors/index.js
test/unit/apps/not-arrived/controllers/letter-received.js

- create new exit page for users who've lost their letter
- redirect to the lost letter page when appropriate
- add accecptance test for lost letter
- update v of hof-controllers in brp
- point letter-received controller at hof-controllers
- utilise base controller fork for letter-received
- check values in letter-received validateField
- remove dependent properties from fields where not working

BRP-78: No letter exit page

---

Dockerfile
run.sh

In theory this should fix the running as root problem.  I haven't tested whether the /public directory will actually be mounted as USER app but it's "supposed to".  However, this is currently broken in the run.sh file anyways.

should allow us to run as root.  Needs tested

---

apps/lost-stolen-damaged/translations/src/en/pages.json

"Text changes requested by Phillip
Change this:
"Once you have submitted this information, we shall cancel your lost or
stolen BRP. If you find the BRP you report as lost or stolen, you will
not be able to use it. You must get a replacement card."
To this:
"Once you have submitted this information, we will cancel your BRP. If
you find the BRP you reported as lost or stolen, you will not be able to
use it and may need to apply for a replacement.""

[BRP-114] Text change on Lost/Stolen journey

---

apps/someone-else/translations/src/en/pages.json

"Nominate: Change heading on cancel nomination page
On this page:
https://www.biometric-residence-permit.service.gov.uk/someone-else/exit-cancel-request
Change the heading from: You cannot use this service
To : You don’t need to use this service"

[BRP-117] Change heading on cancel nomination page

---

acceptance_tests/features/DeliveryFormStep02Validation.feature
acceptance_tests/features/step_definitions/A_Common_Reusable_Steps.rb
acceptance_tests/features/step_definitions/DeliveryFormStep03.rb
acceptance_tests/features/step_definitions/DeliveryFormStep04.rb
apps/common/translations/src/en/common-fields.json
apps/common/translations/src/en/validation.json
apps/not-arrived/fields/address-match.js
apps/not-arrived/steps.js
apps/not-arrived/views/confirm.html
apps/not-arrived/views/same-address-details.html
services/email/templates/caseworker/html/delivery.mus
services/email/templates/caseworker/plain/delivery.mus
services/email/templates/customer/html/delivery.mus
services/email/templates/customer/plain/delivery.mus

"Delivery journey: Case ID for new addresses
If a user requests that their BRP is delivered to a different address to the one used in the initial application, then they MUST provide the 'case reference number' found on their decision letter from the Home Office.
USE THIS COPY:
Case ID number
(Enter the case ID found on your visa decision letter.)
[Error message:]
A case ID number is required for your BRP to be sent to a different address"
Note: This commit touches the "delivery" e-mails and so they should be checked manually prior to merging.

[BRP-104] Add Case ID for new addresses in Delivery

---

package.json
services/email/index.js

This is not really needed in the email service and it's being deprecated from hof.
Version bump hof to 2.0.0

Remove the need for i18n-lookup

---

apps/someone-else/controllers/arrange.js

Displays the correct nominee DOB in the email for the "someone-else"
journey, by preventing the data being over written with junk.
"Wrong nominee DOB in "Someone else" journey e-mail
When selecting "Nominate someone else to collect my BRP" on step one of
the "someone else" journey the DOB you enter for the nominee will be
replaced, in both the customer and case-worker e-mails, with today's
date.
This is probably important as presumably this information is is used to
verify the nominee's date of birth when they come to collect they
BRP."

[BRP-122] Correct nominee DOB in email

---

app.js

The previous implementation was creating a new session store PER request!
This creates one store for the middleware.
The downside to this is we have to check for the dev env variable to serve sessions over HTTP as we otherwise enforse HTTPS.
_How I found the problem_:
Using wrk2 running `wrk2 -R 50000 -d 5m -t 4 -c 300 http://localhost:8080/someone-else`
Which is essentially hitting the server hard for 5minutes
Responded with
```
Running 5m test @ http://localhost:8080/someone-else
4 threads and 300 connections
Thread calibration: mean lat.: 4834.408ms, rate sampling interval: 16752ms
Thread calibration: mean lat.: 4969.476ms, rate sampling interval: 18120ms
Thread calibration: mean lat.: 4837.455ms, rate sampling interval: 16752ms
Thread calibration: mean lat.: 4970.285ms, rate sampling …
```

Fix memory leak.

---

docker-compose.yml

In order to test emails they need to be sent to valid email addresses. Docker compose now sets these email addresses for all journeys to be valid, so they can be picked up by maildev and checked

Updated docker-compose so all emails reach maildev

---

apps/correct-mistakes/views/conditions-and-length.html
apps/correct-mistakes/views/enrolment-letter.html
apps/correct-mistakes/views/exit-truncated.html
apps/not-arrived/views/letter-lost.html
apps/not-arrived/views/letter-not-received.html
apps/not-arrived/views/on-the-way.html
apps/someone-else/views/exit-cancel-request.html
apps/someone-else/views/exit-not-eligible.html

We were restarting forms instead of pushing them off to site surveys.

Ensure that all exit pages to go surveys.

---

app.js

Don't throw when redis recieves an error just log it.
This allows redis-client to retry the connection.

Ensure redis-client reconnects on error

---

apps/collection/views/confirm.html

If there isn't a nominated person, the confirmation page shows an empty h1,
which could potentially be confusing for people relying on screen readers.
On top of that, it could be good to re-evaluate the heading structure of the
page again. It seems to jump between h1 and h3, and could be useful to
re-arrange them as h1-h2-h3 or just use h2's but add h3 classes to them
for visual purposes.

Remove potential empty heading

---

apps/collection/views/where.html

Collection date form elements had an aria-describedby attribute pointing to
the form-hint above. Added the matching id to the form hint.

Fixed broken aria reference to hint on form

---

package.json

This updated hmpo-template-mixins which will address this bug:
https://github.com/UKHomeOffice/brp_app/issues/343

Upgrade hof to latest version.

---

assets/scss/app.scss

This has come up a number of times in user testing and was found to be too small each time.
BRP-139

Increase the steps font size

---

acceptance_tests/features/CollectionFormStep05ChangeDetails.feature

This test was testing forking as a side effect (which was broken)
It should only test returning to the confirm page which it now does.
Forking is a different set of testing issues that can't be tested using this technique.

Remove testing of forking (by accident)

---

assets/js/index.js
assets/scss/app.scss

Visually only display 5 (the rest are visible via overlow).
This is part of the ongoing testing for typeahead. We need to verify how this works out

Show more results for typeahead.

---

apps/collection/translations/src/en/buttons.json
apps/collection/views/confirm.html
apps/common/translations/src/en/buttons.json
apps/correct-mistakes/translations/src/en/buttons.json
apps/correct-mistakes/views/confirm.html
apps/lost-stolen-damaged/translations/src/en/buttons.json
apps/lost-stolen-damaged/views/confirm.html
apps/not-arrived/translations/src/en/buttons.json
apps/not-arrived/views/confirm.html
apps/someone-else/translations/src/en/buttons.json
apps/someone-else/views/confirm.html

When people browse the page in "links mode" they will now be able to see more context rather than just "Change" everywhere

Add hidden content on confirm pages to make it easier to navigate with a screen reader

---

services/email/templates/customer/html/error.mus
services/email/templates/customer/plain/error.mus

This is because we don't know if they have corrected their name.
We don't want to address the customer with their incorrect name!

Don't address the user with their name

---

acceptance_tests/features/CollectionFormChangeWithNominee.feature
acceptance_tests/features/CollectionFormStep04Validation.feature
acceptance_tests/features/CollectionFormStep05ChangeDetails.feature
acceptance_tests/features/DeliveryFormStep03Validation.feature
acceptance_tests/features/DeliveryFormStep05ChangeDetails.feature
acceptance_tests/features/ErrorFormStep06ChangeDetails.feature
acceptance_tests/features/LostStolenDamagedFormStep03Validation.feature
acceptance_tests/features/LostStolenDamagedFormStep05ChangeDetails.feature
acceptance_tests/features/SomeoneElseFormStep01Validation.feature
acceptance_tests/features/SomeoneElseFormStep03Validation.feature
acceptance_tests/features/SomeoneElseFormStep05ChangeDetails.feature
apps/common/views/layout.html
assets/scss/app.scss

At the moment it skips to the phase banner which means it reads (alpha, beta) ever time the user has opted to skip to the main content.
As this is not main content we're going to skip to the step number onwards from now on.

Skip to content should actually skip to the main content

---

acceptance_tests/features/step_definitions/A_Common_Reusable_Steps.rb
acceptance_tests/features/step_definitions/ChangingDeliveryFormDetails_.rb
acceptance_tests/features/step_definitions/ChangingErrorFormDetails_.rb
acceptance_tests/features/step_definitions/ChangingLostStolenDamagedFormDetails_.rb
acceptance_tests/features/step_definitions/CollectionFormStep05_.rb
acceptance_tests/features/step_definitions/DeliveryFormStep04.rb
acceptance_tests/features/step_definitions/SomeoneElseFormStep04_.rb
apps/collection/acceptance/features/_happy-path.js
apps/collection/steps.js
apps/collection/translations/src/en/fields.json
apps/collection/views/confirm.html
apps/collection/views/contact-details.html
apps/common/fields/contact-details.js
apps/correct-mistakes/steps.js
apps/correct-mistakes/translations/src/en/fields.json
apps/correct-mistakes/views/contact-details.html
apps/lost-stolen/steps.js
apps/lost-stolen/translations/src/en/fields.json
apps/lost-stolen/views/confirm.html
apps/lost-stolen/views/contact-details.html
apps/not-arrived/steps.js
apps/not-arrived/translations/src/en/fields.json
apps/not-arrived/views/confirm.html
apps/not-arrived/views/contact-details.html
apps/someone-else/steps.js
apps/someone-else/translations/src/en/fields.json
apps/someone-else/views/confirm.html
apps/someone-else/views/contact-details.html
package.json

This PR adds "happy path" so-acceptance/codecept acceptance tests for the `/collection` app and does not remove the old cucumber acceptance tests.
Also, due to the way that autofil identifies email input fields https://github.com/UKHomeOfficeForms/hof-util-autofill/blob/master/lib/inputs.js#L36 it was necessary change the field `no-email` to `use-address`. therefore this pr also contains many instances of changing that field name.

Add so-acceptance happy path tests for '/collection'

---

apps/correct-mistakes/acceptance/features/_happy-path.js
package.json

- include more deps for so-acceptance
- rename a field s/no-email/use-address to avoid autofill conflicts

Add so-acceptance tests for the '/correct-mistakes' app

---

Dockerfile

The production flag prevents the postinstall script from being run, and so means assets are not compiled in production deployments.

Remove `--production` flag from Docker build postinstall

---

.gitignore
package.json

update jquery for security vulnerability
remove package-lock as we don't use them
I attempted to remove gemfile.lock but this version proved useful for installing and running the cucumber tests.
If gemfile.lock is to be removed it would require more investigation and a separate PR.

update jquery & remove package-lock

---

.dockerignore

This is to trigger a new build, because the last is failing when trying to clone

Ignore documentation from docker

---

services/email/templates/customer/html/delivery.mus

Edit BRP email autoresponder that appears on `/not-arrived` journey
it is causing a lot of additional work for the team handling the enquiries and causing confusion to customers.
Note: * Previous commit didn't quite change the email as expected. This should fix it, hopefully

SD-106 update email template content

---

apps/common/views/error.html
errors/index.js

[https://collaboration.homeoffice.gov.uk/jira/browse/SD-110]
What: The href on the start again button was adding an extra '/' which was causing an error instead of redirecting to a known page when the session had expired and had to be restarted.
Why: After a session timeout the attached screen is shown.  But clicking the start again button fails.

SD 110: 'Start Again' button after session timeout fails

---

apps/common/views/layout.html

Ticket: https://collaboration.homeoffice.gov.uk/jira/browse/SD-480
Removes script which initiates GA tag tracking from layout file used across all routes
At request of the Cabinet Office to become GDPR compliant

SD-480: remove GA Tracking script from custom layout

---

apps/common/fields/personal-details.js

- make sure all EEA countries appear when selecting nationality in personal details
the fact that EEA Nationals are not available on the BRP reporting forms is starting to become an issue and we are aware of an increasing need for us to provide the facility
modified personal-details.js to accept all countries so that it includes ER countries
Tested locally through all app routes

SD-798 Add nationalities to drop down list

---

apps/common/views/partials/page-header.html

**What?**
Removed html header tags from the url header. 
**Why?**
Header tags should be not visible to user.
**Testing?**
Tested locally

Remove html tags on url header

---

apps/not-arrived/behaviours/change-path.js
apps/not-arrived/fields/letter-received.js
apps/not-arrived/index.js
apps/not-arrived/translations/src/en/fields.json
apps/not-arrived/translations/src/en/pages.json
apps/not-arrived/views/collection.html
apps/not-arrived/views/letter-received.html
test/_features/brp/not_arrived.feature
test/_features/step_definitions/steps.js

**What** 
Including a question asking the customer 'Were you due to collect your document form the Post Office?'. If so, they can be redirected to the "Collections" journey. 
**Why**
So that the customer doesn't have to wait to be redirected by a decision maker after 5 days+.
**How** 
The landing URI has been changed to not-arrived/collection with an option which redirects to the /collection URI if the 'yes' option is chosen, otherwise continues the journey as normal. 
**Testing**
Adapted acceptance test to check validation fails and run linting tests.

Brp-6 Including redirect to collection journey 

---

.snyk
apps/collection/fields/index.js
apps/collection/translations/src/en/validation.json
apps/common/fields/organisation-details.js
apps/common/fields/personal-details.js
apps/common/translations/src/en/validation.json
apps/lost-stolen/fields/personal-details.js
apps/lost-stolen/translations/src/en/validation.json
apps/not-arrived/translations/src/en/validation.json
apps/someone-else/fields/arrange.js
apps/someone-else/translations/src/en/validation.json
test/_features/brp/collection_form.feature
test/_features/brp/correct_mistakes.feature
test/_features/brp/lost_stolen.feature
test/_features/brp/not_arrived.feature
test/_features/brp/someone_else.feature
test/_unit/apps/common/validation/validation.spec.js

What?
Added notUrl check to Full Name, Passport Number, BRP Number and Nominated Persons ID Number
Why?
To ensure malicious website URLs do not get sent in the emails that are generated by the backend processes
How?
notUrl validation rule is used
Testing?
Tested manually. Also all existing unit tests and automation tests are passing. 
Screenshots (optional)
N/A
Anything Else?
N/A

Added notUrl check to Full Name, Passport Number, BRP Number etc

---

apps/lost-stolen/fields/personal-details.js

Fix the brp validation so that entering a BRP number is optional on the lost-stolen route on the personal details page.

BRP-35-fix-optional

---

services/email/templates/caseworker/html/error.mus
services/email/templates/caseworker/plain/error.mus

Error details were missing from some BRP submissions
Discovered this was on the recently added new fields. Updated email templates to properly capture this information.

BRP-53-missing-error-details

---

.snyk
apps/lost-stolen/fields/date-lost.js
apps/lost-stolen/translations/src/en/fields.json
apps/lost-stolen/translations/src/en/validation.json
test/_features/brp/lost_stolen.feature

What
Added after validator to date lost field in lost-stolen journey to stop user from entering a date before the launch of Biometric Residence Permits.
Why
Users were able to enter a date into the lost field before the launch of biometric residence permits
Testing
Added acceptance test and tested locally

BRP-26-add after validator to date lost field and acceptance test

---

.snyk
apps/collection/views/confirm.html
services/email/templates/caseworker/html/collection.mus

What 
Changed confirm view to use the value of the reason radio as the label and changed email template so the value of the reason radio is sent to recipient
Why 
on /reasons the user selects a radio button which opens an optional text input. If the user selects a radio button but does not input anything in the optional text input, reasons on the /confirm page will be blank.
Testing 
Tested locally and on branch
Anything else?
Snyk vulnerability SNYK-JS-ASYNC-2441827 added to synk ignore file and has been raised as a ticket

BRP-46 reason displays as blank on /confirm

---

.snyk
kube/app/deployment.yml
package.json
yarn.lock

What
Changed secret key ref name from smtp to ses
Why
The newly rotates AWS SES keys are being named ses in secrets
How
Changed secret key ref name from smtp to ses in the deployment file
Test
Manual testing in local and branch

Changed secret key ref name to ses

---

.drone.yml
apps/collection/fields/index.js
apps/collection/translations/src/en/journeys.json
apps/collection/translations/src/en/pages.json
apps/correct-mistakes/fields/uk-address.js
apps/lost-stolen/fields/personal-details.js
apps/not-arrived/fields/address-match.js
apps/not-arrived/fields/letter-received.js
apps/not-arrived/index.js
apps/not-arrived/translations/src/en/buttons.json
apps/not-arrived/translations/src/en/fields.json
apps/not-arrived/translations/src/en/pages.json
apps/not-arrived/views/confirm.html
apps/not-arrived/views/letter-received.html
apps/someone-else/fields/reason.js
services/email/templates/caseworker/html/collection.mus
services/email/templates/caseworker/html/delivery.mus
services/email/templates/caseworker/html/error.mus
services/email/templates/caseworker/html/lost_or_stolen.mus
services/email/templates/caseworker/html/someone-else.mus
services/email/templates/caseworker/plain/delivery.mus
test/_features/brp/not_arrived.feature

**Changes**
- letter-received.html updated to include new case-id-number fields in not-arrived route.
- new case-id-number fields added to pages.json, fields.json, and index.js within not-arrived route.
- Email templates changed to include a comma after the field name, and updated to include all fields in the email with 'None Given' for fields with no information obtained from the user.
- Updated acceptance tests to include the new case-id-number field.
- Fixed data issues with email, phone number and county address not appearing on emails on all routes.
**Reason**
Changes above requested by the business.

BRP-95: Add case ID to not-arrived letter-received route and reformat caseworker emails

---

services/email/templates/caseworker/html/collection.mus
services/email/templates/caseworker/html/delivery.mus
services/email/templates/caseworker/html/error.mus
services/email/templates/caseworker/html/lost_or_stolen.mus
services/email/templates/caseworker/html/someone-else.mus

**Changes**
- Changes made to address format on the email. 
- Changes made to "help-from" on all routes so default text 'None Given' is shown in the email when user does not give any sponsor information.
**Reason**
- Changes requested by the business as follow up changes from ticket BRP-95. 
**Testing**
- Tested by QAT on branch.

BRP-98: Changes to the email templates on all routes

---

apps/lost-stolen/fields/personal-details.js

What?
BRP-Lost-stolen-Full name is optional field however in all other BRP routes its mandatory field.
How?
Updated fullname validator to be required
```
fullname: {
validate: ['required', 'notUrl']
},
```
Testing?
Running `npm run test`
Screenshots?

BRP-67: Make Fullname mandatory

---

.drone.yml

What?
I've added Trivy Scanner to Pipeline and removed deprecated Anchore Scanner for the BRP enquiry service, see ticket
[https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-614](url)
Why?
Trivy will let you scan images, file systems and repositories for any vulnerabilities and issues. It will detect CVEs of OS packages, applications susceptibilities, and exposures of IaC in Terraform files, Kubernetes and Docker.
Drawback of Anchore Scanner is it’s significantly slower, the process of using it is more cumbersome, the output is less friendly and most importantly, it scans fewer CVEs.
See [https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-614](url) for more information.
How?
Removed Anchore cve exception file and added trivy cve exception file in hof-services-config repo from …

HOFF-614: Replace Anchore with Trivy

---

.drone.yml

A deployment is being made to whitelisted IP's so it's not accessed from the public
deploying to implement changes

made some changes so uat is deployed

---

apps/collection/fields/index.js
apps/correct-mistakes/fields/uk-address.js
apps/lost-stolen/fields/personal-details.js
apps/lost-stolen/translations/src/en/emails.json
apps/not-arrived/fields/address-match.js
apps/someone-else/fields/reason.js

-  Change input type for phone number fields - [BRP-131](https://collaboration.homeoffice.gov.uk/jira/browse/BRP-131)
- The type value for the phone number textbox is set as "text" when it should be set as "tel".
- Add 'tel' type to phone fields config
- Tests passing locally
Before change:
After change:
- Remove duplicate properties in lost-stolen/emails.json

BRP-131: Change input type for phone numbers

---

.snyk
apps/common/views/accessibility.html

Update the accessibility statement for the BRP form - [HOFF-943](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-943)
To reflect the latest accessibility tests against WCAG 2.2
Updated the `apps/common/views/accessibility.html` file
Tested locally
N/A

HOFF-943: Update accessibility statement for BRP

---

apps/lost-stolen/translations/src/en/emails.json
services/email/templates/customer/html/lost_or_stolen_abroad.mus
services/email/templates/customer/html/lost_or_stolen_uk.mus
services/email/templates/customer/plain/lost_or_stolen_abroad.mus
services/email/templates/customer/plain/lost_or_stolen_uk.mus

Updated content of emails for the lost-stolen journey in the BRP form - [BRP-134](https://collaboration.homeoffice.gov.uk/jira/browse/BRP-134)
To reflect the latest required email content changes in the form
- Updated email content in `/apps/lost-stolen/translations/src/en/emails.json`
- Updated references to the email content in:
`/services/email/templates/customer/html/lost_or_stolen_abroad.mus`, `/services/email/templates/customer/html/lost_or_stolen_uk.mus`, `/services/email/templates/customer/plain/lost_or_stolen_abroad.mus`, `services/email/templates/customer/plain/lost_or_stolen_uk.mus`
Tested locally
Inside UK email:
Outside UK email:

BRP-134: Updated emails for lost/stolen BRP

---

.drone.yml
bin/deploy.sh
kube/app/ingress-external-restriction.yml
kube/app/ingress-internal.yml

GDS is decommissioning error correction via https://www.biometric-residence-permit.service.gov.uk/correct-mistakes/location, so this is to add restriction to public access.
[EEC-28](https://collaboration.homeoffice.gov.uk/jira/browse/EEC-28) - BRP Error webform - restrict IPS and removal of all links
Adding a secondary ingress restricts to that path
See if access is indeed restricted

EEC-28: BRP Error webform - restrict IPS

---

kube/app/ingress-external-restriction.yml

Added a name for /correct-mistakes ingress
to stop it overriding the generic ingress when deployed

Set a different name for correct-mistakes ingress

---

apps/collection/index.js
apps/common/index.js
apps/common/views/404.html
apps/correct-mistakes/index.js
apps/lost-stolen/index.js
apps/not-arrived/index.js
apps/someone-else/index.js
hof.settings.json
package.json
services/email/index.js
yarn.lock

- BRP-149: Update BRP to HOF version with Session Timeout Warning - [BRP-149](https://collaboration.homeoffice.gov.uk/jira/browse/BRP-149)
- BRP-150: Update BRP to latest HOF version to fix nodemailer vulnerability - [BRP-150](https://collaboration.homeoffice.gov.uk/jira/browse/BRP-150)
- BRP-149: To comply with WCAG 2.2 accessibility requirements
- BRP-150: To fix nodemailer security vulnerability
BRP-149
- Update hof to version ~22.0.0 to implement session timeout message
- add hof session timeout behaviour to hof.settings.json
- add '/exit' steps to index.js of each journey
- add '/session-timeout' step to common/index.js
- amend 404.html to static page so it does not display session timeout message 
BRP-150
- update hof to version ~22.1.1 to implement nodemailer vulnerability fix
- …

BRP-149 and BRP-150: Update BRP to latest HOF version

---

.snyk
apps/common/views/accessibility.html

Updated service accessibility statement.  
https://collaboration.homeoffice.gov.uk/jira/browse/BRP-151
- removed reference of session timeout; updated last review date (accessibility.html)

BRP-151: Update Accessibility Statement

---

kube/redis/redis-deployment.yml

* Following changes has been done to Redis image
*  Upgraded Redis from 5.0.6 to 7.0.15 and tagged image accordingly.
*   Switched base image from Fedora to Rocky Linux 9.3 due to Trivy support.
*  Done sanity checks on BRP and is working as expected.
*  Refer to https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1224
* Further information added to description of Jira ticket
**Upgrading Redis to 7.0.15**
Security Fixes: Redis 5.0.6 is quite old and has known vulnerabilities. Upgrading to 7.0.15 ensures you're protected against those and benefits from the latest security patches.
Performance Improvements: Newer Redis versions often include performance optimizations and bug fixes that improve stability and efficiency.
Feature Enhancements: Redis 7.x introduces new features like ACL …

HOFF-1225: Use latest redis docker image with fixed vulnerabilties
